apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.catalog.name}}
  labels:
    app: {{.Values.catalog.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.catalog.name}}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.catalog.name}}"
        dapr.io/app-port: "80"
        dapr.io/log-as-json: "true"
        dapr.io/config: "dapr-config"
      labels:
        app: {{.Values.catalog.name}}
    spec:
      containers:
      - name: {{.Values.catalog.name}}
        image: {{.Values.catalog.image}}:{{.Values.catalog.tag}}
        imagePullPolicy: Never
        ports:
        - containerPort: 80