apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.website.name}}
  labels:
    app: {{.Values.website.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.website.name}}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.website.name}}"
        dapr.io/app-port: "80"
        dapr.io/log-as-json: "true"
        dapr.io/config: "dapr-config"
      labels:
        app: {{.Values.website.name}}
    spec:
      containers:
      - name: {{.Values.website.name}}
        image: {{.Values.website.image}}:{{.Values.website.tag}}
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.website.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.website.name}}
  ports:
    - protocol: TCP
      port: {{.Values.website.port}}
      targetPort: 80
      name: http
  type: LoadBalancer