apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.name}}-dapr"
        dapr.io/app-port: "80"
        dapr.io/log-as-json: "true"
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.deployment.image}}:{{.Values.deployment.tag}}
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: 80
  type: LoadBalancer