apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: access-secrets
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update", "create"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-to-secrets
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: microkart-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets