apiVersion: v1
kind: Secret
metadata:
  name: microkart-app-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  SA_PASSWORD: In%^$India&8$
  IDENTITY_DB_CONNECTION: Server={{.Values.database.dbserver}}.microkart-app-database;Database=IdentityDb;User Id=sa;Password=In%^$India&8$
  CALATOG_DB_CONNECTION: Server={{.Values.database.dbserver}}.microkart-app-database;Database=CatalogDb;User Id=sa;Password=In%^$India&8$
  BASKET_DB_CONNECTION: Server={{.Values.database.dbserver}}.microkart-app-database;Database=BasketDB;User Id=sa;Password=In%^$India&8$
