apiVersion: v1
kind: Secret
metadata:
  name: microkart-app-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  SA_PASSWORD: In%^$India&8$
  IDENTITY_DB_CONNECTION: Server={{.Values.dbserver}};Database=IdentityDb;User Id=sa;Password=In%^$India&8$
