# config.yaml
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx

ui:
  ingress:
    enabled: true
    path: /
    hosts:
      - seq.microkart.com


ingestion:
  ingress:
    enabled: true
    path: /
    hosts:
      - ingestion.seq.microkart.com