apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.persistentvolume.name}}
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /data/sqlpv/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.persistentvolume.name}}-claim
  namespace: {{.Values.namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi