apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /data/sqlpv/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlpv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi