apiVersion: apps/v1
kind: Deployment
metadata:
  name: microkario-catalog
  labels:
    app: microkario-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microkario-catalog
  template:
    metadata:
      labels:
        app: microkario-catalog
    spec:
      containers:
      - name: microkariocatalog
        image: microkart.catalog:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microkario-catalog
spec:
  selector:
    app: microkario-catalog
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 80
  type: LoadBalancer